version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-push:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            cd server &&
            sh ./scripts/push.sh
workflows:
  build-push:
    jobs:
      - build-push:
          context: secrets
