apiVersion: apps/v1
kind: Deployment
metadata:
  name: new
  labels:
    app: myapp
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ""
          imagePullPolicy: Always
          ports:
            - name: http-ports
              containerPort: 4000
