version: '3'

services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    depends_on: 
      - db

  db:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'database'
    ports:
      - "3306:3306"
      