# USER
type User {
  id: Int!
  name: String!
}

input UserInput {
  id: Int
  name: String!
}
# END USER



# TAG
type Tag {
  id: Int!
  value: String!
  label: String!
}

input CreateTagInput {
  id: Int
  value: String!
  label: String!
}

input ReadTagInput {
  search: String
}
# END TAG



# TODO
type Todo {
  id: Int!
  user: User!
  title: String!
  content: String!
  created_at: String!
  updated_at: String!
  tags: [Tag]!
}

input ReadTodoInput {
  user: Int!
  search: String
  tags: [IDInput!]
}

input CreateTodoInput {
  id: Int
  user: UserInput!
  title: String!
  content: String!
  tags: [CreateTagInput!]
}

input IDInput {
  id: Int!
}
# END TODO



type Query {
  hello(id: ID): [User]

  createUser(data: UserInput!): User

  createTag(data: CreateTagInput!): Tag
  readTag(data: ReadTagInput!): [Tag]!
  deleteTag(data: IDInput!): Boolean!

  createTodo(data: CreateTodoInput!): Todo
  readTodo(data: ReadTodoInput!): [Todo]!
  updateTodo(data: CreateTodoInput!): Todo
  deleteTodo(data: IDInput!): Boolean!
}
