type User {
  id: Int!
  name: String!
}

input UserInput {
  id: Int
  name: String!
}



type Tag {
  id: Int!
  value: String!
  label: String!
}

input TagInput {
  id: Int
  value: String!
  label: String!
}

type Todo {
  id: Int!
  user: User!
  content: String!
  created_at: Int!
  updated_at: Int!
  tags: [Tag]
}

input TodoInput {
  user: UserInput!
  content: String!
  created_at: Int!
  updated_at: Int!
  tags: [TagInput]
}

type Query {
  hello(id: ID): User
  addUser(data: UserInput): User
  addTag(data: TagInput): Tag
  addTodo(data: TodoInput): Todo
}
