# USER
type User {
  id: Int!
  name: String!
}

input UserInput {
  id: Int
  name: String!
}
# END USER



# TAG
type Tag {
  id: Int!
  value: String!
  label: String!
}

input TagInput {
  id: Int
  value: String!
  label: String!
}
# END TAG



# TODO
type Todo {
  id: Int!
  user: User!
  content: String!
  created_at: String!
  updated_at: String!
  tags: [Tag]!
}

input NewTodoInput {
  user: UserInput!
  content: String!
  tags: [TagInput!]
}

input EditTodoInput {
  id: Int!
  content: String!
  tags: [TagInput!]
}

input DeleteTodoInput {
  id: Int!
}
# END TODO



type Query {
  hello(id: ID): User

  addUser(data: UserInput!): User
  addTag(data: TagInput!): Tag

  addTodo(data: NewTodoInput!): Todo
  editTodo(data: EditTodoInput!): Todo
  deleteTodo(data: DeleteTodoInput!): Boolean!
}
